name       : qt5-location
version    : 5.15.1
release    : 25
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qtlocation-everywhere-src-5.15.1.tar.xz : 093af763a70d126c4b9f6a22ebf8218fe95dc0151e40666b2389fdf55c9f1a2c
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Location and Mapping Components
description: |
    The Qt Location API helps you create viable mapping solutions using the data available from some of the popular location services.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtlocation.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
