name       : qt5-location
version    : 5.12.1
release    : 16
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtlocation-everywhere-src-5.12.1.tar.xz : 8b922373e6eefd1b0e2a993dbf3d0b3f3df777bc720d40cad3ccb46e1936bc50
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Location and Mapping Components
description: |
    The Qt Location API helps you create viable mapping solutions using the data available from some of the popular location services.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtlocation.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
