name       : qt5-location
version    : 5.15.4
release    : 38
source     :
    - git|https://invent.kde.org/qt/qt/qtlocation.git : 73db91329ae48f685fa3fdae1c3c63b0976dc751
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 Location and Mapping Components
description: |
    The Qt Location API helps you create viable mapping solutions using the data available from some of the popular location services.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    # revert 5.15.5 merge
    git revert -m 1 ddf3f88156369671576a9bcc703feb22e7b7ff0d
    %qmake CONFIG+=release qtlocation.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
