name       : qt5-location
version    : 5.13.1
release    : 20
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.1/submodules/qtlocation-everywhere-src-5.13.1.tar.xz : 16bd4d64b12fc3f8276fe37985f2b0f5443317c882937ab5e0b583a3a9eed298
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Location and Mapping Components
description: |
    The Qt Location API helps you create viable mapping solutions using the data available from some of the popular location services.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtlocation.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
