name       : qt5-location
version    : 5.13.2
release    : 22
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qtlocation-everywhere-src-5.13.2.tar.xz : 5fe4b824d3dc6c800682ff986333ec09edb9c27582066e928b1862b4d58212e3
homepage   : https://www.qt.io
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Location and Mapping Components
description: |
    The Qt Location API helps you create viable mapping solutions using the data available from some of the popular location services.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtlocation.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
