name       : qt5-location
version    : 5.11.1
release    : 13
source     :
    - https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.11/5.11.1/submodules/qtlocation-everywhere-src-5.11.1.tar.xz : 172c9a39e8267739e20d60bda45de3db02b13163245776bdc696d8c5ab5f790f
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Location and Mapping Components
description: |
    The Qt Location API helps you create viable mapping solutions using the data available from some of the popular location services.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtlocation.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
